spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshop?useUnicode=true&serverTimezone=UTC
    username: root
    password: admin123
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true