spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshop?useUnicode=true&serverTimezone=UTC
    username: root
    password: admin123
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
server:
  error:
    include-message: always
    include-binding-errors: always

app:
  uploadDir: ./data/productImages/